services:
  db:
    container_name: postgres
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
